<?php $detailPosted=(string)($posted['id']??'')===(string)$r['id']?$posted:[];$legacy=str_starts_with($r['id'],'test:');$v=$detailPosted&&($detailPosted['action']??'')==='edit'?$detailPosted:$r; ?>
<section class="nf-card intake-detail-card" data-intake-detail-panel data-intake-record="<?= $eh($r['id']) ?>"><h2>접수 상세 · <?= $eh($r['customer']) ?> <?= $r['isTest']?'<span class="intake-test">테스트</span>':'' ?></h2>
<aside class="intake-side-search" data-intake-side-search data-scope="<?= $eh($filters['scope']) ?>">
<label>이름·전화번호 검색<input type="search" data-intake-search-input maxlength="80" autocomplete="off" placeholder="입력하면 바로 검색" aria-label="접수증 이름 또는 전화번호 검색"></label>
<p data-intake-search-status role="status" aria-live="polite">이름 또는 전화번호를 입력해 주세요.</p><div data-intake-search-results></div>
</aside>
<?php if(!$legacy):
$editValues=[];foreach(['customer','phone','birthDate','birthYear','carrier','consultationTime','consultationPlace','premiumBand','note','gender','callAvailability','visitSchedule','counselorName','status'] as $key)$editValues[$key]=(string)($v[$key]??$r[$key]??'');
$editValues+=['id'=>$r['id'],'date'=>$r['date'],'employee'=>$r['employee'],'team'=>$r['team'],'reason'=>(string)(($detailPosted['action']??'')==='edit'?($detailPosted['reason']??''):'')];
$editData=['record'=>$editValues,'counselorNames'=>$snapshot['counselorNames']??[]];
?><details class="intake-edit" open><summary>상담원·승인 상태·접수 내용 수정</summary>
<div class="receipt-host" data-intake-edit-host data-intake-edit-url="<?= $eh(intake_url($filters,['id'=>$r['id']])) ?>">
<template data-intake-edit-data><?= $eh(json_encode($editData,JSON_UNESCAPED_UNICODE|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_THROW_ON_ERROR)) ?></template>
<template data-intake-edit-hidden><?= native_csrf() ?><input type="hidden" name="action" value="edit"><input type="hidden" name="id" value="<?= $eh($r['id']) ?>"><input type="hidden" name="revision" value="<?= $eh($detailPosted['revision']??$r['revision']) ?>"></template>
<div data-intake-edit-form><p role="status">접수 입력 양식을 불러오고 있습니다.</p><noscript><p>접수 내용을 수정하려면 자바스크립트를 활성화해 주세요.</p></noscript></div>
</div></details><?php else: ?><p class="nf-muted">이전 형식의 테스트 자료는 상태만 변경할 수 있습니다.</p><?php endif ?>
<details class="intake-original"><summary>접수 기본 정보</summary><dl class="intake-detail-grid">
<?php foreach(['접수번호'=>$r['id'],'접수일'=>$r['date'],'담당자'=>$r['employee'],'상담원'=>$r['counselorName']??'','부서'=>$teams[$r['team']],'상태'=>intake_status($r['status']),'생년월일'=>($r['birthDate']??'')?:($r['birthYear']??'미입력'),'고객명'=>$r['customer'],'전화번호'=>$r['phone']??'미입력','상품 구분'=>$r['kind']==='silver'?'실버':($r['kind']==='general'?'일반':'—'),'접수 코드'=>$r['carrier']??'','상담 시간'=>$r['consultationTime']??'','지역(동)'=>$r['consultationPlace']??'','성별'=>$r['gender']??'','통화 가능시간'=>$r['callAvailability']??'','방문 일정·장소'=>$r['visitSchedule']??'','월보험료'=>$premium[$r['premiumBand']??'']??'미입력','등록 시각'=>empty($r['receivedAt'])?'':intake_time($r['receivedAt'])] as $label=>$value): ?><div><dt><?= $eh($label) ?></dt><dd><?= $eh($value?:'—') ?></dd></div><?php endforeach ?></dl></details>
<details class="intake-memo-history"><summary>상담 메모 · 재콜 이력</summary><p><strong>최초 메모</strong><br><?= nl2br($eh(($r['note']??'')?:'등록된 메모가 없습니다.')) ?></p><?php foreach(array_reverse($history) as $event): if(!in_array($event['action'],['memo','recall','resubmit','hold'],true))continue; ?><section><p><strong><?= $eh(substr(intake_time($event['created_at']),0,16)) ?> · <?= $eh($event['actor']) ?></strong> · <?= ['memo'=>'메모 추가','recall'=>'재콜 수정 요청','resubmit'=>'재접수 요청','hold'=>'가접수 유지'][$event['action']] ?></p><p><?= nl2br($eh($event['reason'])) ?></p></section><?php endforeach ?></details>
<?php if(!$legacy&&!empty($r['phone'])): $phone=preg_replace('/\D/','',$r['phone']);$duplicates=count(array_filter($snapshot['records'],fn($row)=>$row['id']!==$r['id']&&$row['isTest']===$r['isTest']&&str_starts_with($row['date'],$filters['month'])&&preg_replace('/\D/','',$row['phone']??'')===$phone&&sales_customer_key($row['customer'])===sales_customer_key($r['customer'])));if($duplicates): ?><p class="nf-alert">같은 이름과 전화번호의 다른 접수가 이달 <?= $duplicates ?>건 있습니다. 중복 여부를 확인하세요.</p><?php endif;endif ?>
<?php if($legacy): ?><form method="post" action="<?= $eh(intake_url($filters,['id'=>$r['id']])) ?>" class="nf-actions"><?= native_csrf() ?><input type="hidden" name="action" value="status"><input type="hidden" name="id" value="<?= $eh($r['id']) ?>"><input type="hidden" name="revision" value="<?= $eh($detailPosted['revision']??$r['revision']) ?>"><label class="nf-field">처리 상태<select name="status"><?php foreach(array_slice($statuses,1) as $key=>$label): ?><option value="<?= $key ?>" <?= ($detailPosted['status']??$r['status'])===$key?'selected':'' ?>><?= $label ?></option><?php endforeach ?></select></label><label class="nf-field">처리 메모 (선택)<input name="reason" maxlength="500" value="<?= $eh(($detailPosted['action']??'')==='status'?($detailPosted['reason']??''):'') ?>" placeholder="상태 변경 사유"></label><button type="submit">상태 저장</button></form>
<?php endif ?>
<?php if($r['status']==='pending'): ?><form method="post" action="<?= $eh(intake_url($filters,['id'=>$r['id']])) ?>" class="nf-actions"><?= native_csrf() ?><input type="hidden" name="action" value="hold"><input type="hidden" name="id" value="<?= $eh($r['id']) ?>"><input type="hidden" name="revision" value="<?= $eh($detailPosted['revision']??$r['revision']) ?>"><input type="hidden" name="status" value="pending"><label class="nf-field">가접수 유지 사유<input name="reason" maxlength="500" placeholder="추가 상담, 고객 연락 대기 등"></label><button type="submit">확인 후 가접수 유지</button></form><?php endif ?>
<details class="intake-history"><summary>등록·변경 이력 (최근 <?= count($history) ?>건)</summary><?php if(!$history): ?><p class="nf-muted">아직 기록된 변경 이력이 없습니다.</p><?php endif ?>
<?php $names=['customer_name'=>'고객명','phone'=>'전화번호','carrier'=>'접수 코드','note'=>'접수 메모','consultation_time'=>'상담 시간','consultation_place'=>'상담 장소','premium_band'=>'납부 보험료','status'=>'상태','date'=>'최초 접수일','gender'=>'성별','callAvailability'=>'통화 가능시간','visitSchedule'=>'방문 일정·장소','counselorName'=>'상담원','birth_date'=>'생년월일','birth_year'=>'출생연도','insurance_kind'=>'상품 구분'];foreach($history as $event): ?><section><p><strong><?= $eh(intake_time($event['created_at'])) ?> · <?= $eh($event['actor']) ?></strong> · <?= ['create'=>'접수 등록','status'=>'상태 변경','edit'=>'정보 수정','hold'=>'가접수 유지','memo'=>'메모 추가','recall'=>'재콜 수정 요청','resubmit'=>'재접수 요청'][$event['action']]??'처리' ?></p><dl><?php foreach($event['after'] as $key=>$value): $before=$event['before'][$key]??'';if($before===$value||$key==='recallEventId')continue; ?><dt><?= $eh($names[$key]??$key) ?></dt><dd><?= $eh($key==='status'?intake_status($before):($key==='insurance_kind'?(['general'=>'일반','silver'=>'실버'][$before]??$before):$before)) ?> → <?= $eh($key==='status'?intake_status($value):($key==='insurance_kind'?(['general'=>'일반','silver'=>'실버'][$value]??$value):$value)) ?></dd><?php endforeach ?></dl><?php if($event['reason']): ?><p>메모: <?= nl2br($eh($event['reason'])) ?></p><?php endif ?></section><?php endforeach ?></details></section>
