const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(require('node:path').join(__dirname,'office.js'),'utf8');
const start=html.indexOf('function policyConfirmedCropReading('),end=html.indexOf('async function policyRecognizeBatch(',start);
const context=vm.createContext({});vm.runInContext(html.slice(start,end),context);
const {policyConfirmedCropReading:confirm,policyNameNeedsReview:review}=context;
const r=(text,confidence,family)=>({text,confidence,family});const pat=/^[가-힣]{2,4}$/;
let cases=0;const check=(condition)=>{assert.ok(condition);cases++};
const independent=[r('광주',96,'whitepixel'),r('광주',93,'white'),r('광무',77,'color')];
const agreed=confirm(independent,pat);check(agreed.text==='광주'&&agreed.confidence===96);
check(review(agreed,r('광주',78),r('광무',87),true,false)===false);
check(confirm([r('광주',96,'color'),r('광주',94,'color')],pat)===null);
check(confirm([r('광주',96,'whitepixel'),r('광주',84,'white')],pat)===null);
check(confirm([r('광주',96,'whitepixel'),r('광무',93,'white'),r('광모',89,'color')],pat)===null);
check(review(r('광주',84),r('광주',84),r('광주',84),true,false)===true);
check(review(r('필 #',96),r('필 #',96),r('필 必',96),true,false)===true);
check(review(r('충남서부 : 서산시 必',95),r('충남서부 : 서산시 #',95),r('충남서부 : 서산시 必',95),false,false)===true);
check(review(r('충남서부 : 서산시 必',95),r('충남서부 : 서산시 #',95),r('충남서부 : 서산시 #',95),false,true)===true);
check(review(r('충남서부 : 서산시 必',95),r('충남서부 : 서산시 #',95),r('충남서부 : 서산시 #',95),false,false)===false);
check(review(r('',95),r('',95),r('',95),true,false)===true);
check(review(r('서울',93),r('서 울',93),r('서울',93),false,false)===false);
check(confirm([r('광주',96,'a'),r('광주',95,'b'),r('광무',96,'c'),r('광무',95,'d')],pat)===null);
const scripts=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(x=>x[1]);for(const script of scripts)new vm.Script(script);
console.log(`${cases} OCR review gate cases passed; ${scripts.length} inline scripts parse.`);
