(()=>{'use strict';
if(window.CNCHOME_LIVE?.user?.role!=='employee')return;
let rows=[],busy=false,queued=null,index,feedback='';const expanded=new Set(),drafts=new Map();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function evaluatedRows(){
 const core=window.IntakeDetails?.core;if(!core)return [];
 index??=core.placeIndex(window.KoreaRegionCatalog);
 const year=Number(new Intl.DateTimeFormat('en',{year:'numeric',timeZone:'Asia/Seoul'}).format(new Date()));
 return rows.map(r=>{const birth=Number((r.birthDate||'').slice(0,4)||r.birthYear),age=birth?year-birth+1:null,kind=age===null?r.kind:age<=60?'general':age<=70?'silver':null;let result={items:[],text:'지역 확인 필요'};
  try{result=core.assess(window.PolicySync?.snapshot,window.PolicyRegionRules,core.resolveLocation((r.consultationPlace||'').replace(/^\[테스트\]\s*/,''),index),kind,'');}catch(e){}
  return {r,result,kind,codes:core.availableCodes(result.items)};
 }).sort((a,b)=>Number(b.codes.length>0)-Number(a.codes.length>0)||a.r.date.localeCompare(b.r.date)||a.r.id.localeCompare(b.r.id,undefined,{numeric:true}));
}
function render(force=false){
 const el=document.querySelector('[data-pending-list]');if(!el||(!force&&el.contains(document.activeElement)&&document.activeElement.matches('textarea,select')))return;
 const evaluated=evaluatedRows(),possible=evaluated.filter(x=>x.codes.length).length;
 el.innerHTML='<p>현재 적용 정책에 접수 가능한 건 우선 · 최초 접수일이 오래된 순서입니다. 행을 누르면 상세내용과 상담 메모가 펼쳐집니다.</p><div class="pending-intake-meta"><strong>가접수 '+rows.length+'건</strong><span>접수 가능 '+possible+'건</span><span>확인 대기 '+rows.filter(r=>r.recallPending).length+'건</span></div><p class="pending-intake-feedback" role="status">'+esc(feedback)+'</p><div class="scroll"><table class="pending-intake-table"><thead><tr><th>최초 접수일</th><th>고객명</th><th>상담 지역</th><th>현재 정책</th><th>처리 상태</th><th>상세</th></tr></thead><tbody>'+evaluated.map(({r,result,kind,codes},i)=>{
  const isOpen=expanded.has(r.id),draft=drafts.get(r.id)||{},detailId='pending-detail-'+i;
  return `<tr class="pending-intake-row" data-pending-toggle="${esc(r.id)}" aria-expanded="${isOpen}"><td>${esc(r.date)}</td><td><strong>${esc(r.customer)}</strong></td><td>${esc(r.consultationPlace||'지역 미입력')}</td><td><span class="pending-intake-status ${codes.length?'available':'unavailable'}">${codes.length?'접수 가능':'확인 필요'}</span><br><small>${esc(codes.map(c=>c.label).join(' · ')||result.text)}</small></td><td>${r.recallPending?'관리자 확인 대기':'가접수'}</td><td><button type="button" class="pending-intake-toggle" aria-expanded="${isOpen}" aria-controls="${detailId}" aria-label="${esc(r.customer)} 상세 ${isOpen?'접기':'펼치기'}">${isOpen?'접기':'펼치기'}</button></td></tr>
  <tr id="${detailId}" class="pending-intake-detail" ${isOpen?'':'hidden'}><td colspan="6"><div class="pending-intake-meta"><span>연락처 <strong>${esc(r.phone||'미입력')}</strong></span><span>생년월일 ${esc(r.birthDate||r.birthYear||'미입력')}</span><span>상담 시간 ${esc(r.consultationTime||'미입력')}</span><span>접수 코드 ${esc(r.carrier||'미입력')}</span><span>${kind==='silver'?'실버':kind==='general'?'일반':'연령 확인 필요'}</span></div><div class="pending-note-history"><strong>상담 메모</strong><p>${esc(r.note||'기존 메모가 없습니다.')}</p>${(r.memoHistory||[]).map(n=>`<article><small>${esc(n.at)} · ${esc(n.actor)} · ${n.action==='recall'?'재콜 수정':'메모 추가'}</small><p>${esc(n.memo)}</p></article>`).join('')}</div><form class="pending-intake-form" data-pending-id="${esc(r.id)}"><label>메모 이어쓰기<textarea name="memo" maxlength="500" required placeholder="통화 결과나 다음 연락 내용을 입력해 주세요.">${esc(draft.memo||'')}</textarea></label><label>재콜 접수 코드<select name="carrier">${codes.length?codes.map(c=>`<option value="${esc(c.label)}" ${(draft.carrier||r.carrier)===c.label?'selected':''}>${esc(c.label)}</option>`).join(''):'<option value="">접수 가능한 정책 없음</option>'}</select></label><div class="pending-intake-actions"><button type="submit" class="secondary" name="action" value="memo" ${busy?'disabled':''}>메모 추가</button><button type="submit" name="action" value="recall" ${busy||!codes.length||r.recallPending?'disabled':''}>${r.recallPending?'관리자 확인 대기':'재콜 수정'}</button></div></form><p class="pending-intake-feedback">메모는 기존 기록 뒤에 추가됩니다. 재콜 수정은 관리자 정상접수 확인표로 전달됩니다.</p></td></tr>`;
 }).join('')+(!rows.length?'<tr><td colspan="6">현재 가접수가 없습니다.</td></tr>':'')+'</tbody></table></div>';
}
async function load(body){
 const el=document.querySelector('[data-pending-list]');if(busy){if(body){queued=body;el?.querySelectorAll('button[type="submit"]').forEach(b=>b.disabled=true);}return;}busy=true;if(body)el?.querySelectorAll('button[type="submit"]').forEach(b=>b.disabled=true);
 try{const response=await fetch('/pending-intakes.php?role=employee',{method:body?'POST':'GET',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json','X-CSRF-Token':window.CNCHOME_LIVE.csrf},...(body?{body:JSON.stringify(body)}:{})});const data=await response.json();if(!response.ok)throw Error(data.error||'가접수 조회에 실패했습니다.');rows=data.records||[];if(body){const draft=drafts.get(body.id);if(!draft||(draft.memo===body.memo&&draft.carrier===body.carrier))drafts.delete(body.id);feedback=body.action==='memo'?'메모를 기존 기록에 이어 저장했습니다.':'재콜 수정 내용을 관리자 정상접수 확인표로 전달했습니다.';}}
 catch(e){feedback=e.message;}finally{busy=false;render(!!body);if(queued){const next=queued;queued=null;load(next);}}
}
document.addEventListener('click',e=>{const row=e.target.closest('[data-pending-toggle]');if(!row)return;const id=row.dataset.pendingToggle,on=!expanded.has(id);if(on)expanded.add(id);else expanded.delete(id);row.setAttribute('aria-expanded',String(on));const button=row.querySelector('button');button.setAttribute('aria-expanded',String(on));button.textContent=on?'접기':'펼치기';button.setAttribute('aria-label',(rows.find(r=>r.id===id)?.customer||'고객')+' 상세 '+(on?'접기':'펼치기'));row.nextElementSibling.hidden=!on;});
function capture(e){const f=e.target.closest('[data-pending-id]');if(f)drafts.set(f.dataset.pendingId,{memo:f.elements.memo.value,carrier:f.elements.carrier.value});}
document.addEventListener('input',capture);document.addEventListener('change',capture);
document.addEventListener('submit',e=>{const f=e.target.closest('[data-pending-id]');if(!f)return;e.preventDefault();const r=rows.find(r=>r.id===f.dataset.pendingId),action=e.submitter?.value||'memo';if(!r||!f.reportValidity())return;load({id:r.id,revision:r.revision,action,memo:f.elements.memo.value,carrier:f.elements.carrier.value});});
const observer=new MutationObserver(()=>{const el=document.querySelector('[data-pending-list]');if(el&&!el.dataset.loaded){el.dataset.loaded='1';load();}});const main=document.getElementById('tm-main');if(main)observer.observe(main,{childList:true,subtree:true});window.PolicySync?.subscribe(()=>render());if(document.querySelector('[data-pending-list]'))load();setInterval(()=>{if(document.querySelector('[data-pending-panel][open]'))load();},15000);
})();
document.addEventListener('toggle',e=>{if(e.target.matches?.('.region-map-disclosure')&&e.target.open)window.dispatchEvent(new Event('resize'));},true);
