<?php
$popup=$popup??false;$recallQueue=$recallQueue??[];
$teams=[''=>'전체 부서','insurance'=>'보험팀','cosmetics'=>'화장품팀','health'=>'건강보조식품팀'];$statuses=[''=>'전체 상태','pending'=>'가접수','normal'=>'정상접수','as'=>'A/S'];$premium=[''=>'미입력','100000'=>'10만 원 이상','200000'=>'20만 원 이상','300000'=>'30만 원 이상'];
$eh=fn(mixed $v):string=>view_h((string)$v);
$field=function(string $name,string $label,mixed $value='',string $type='text',int $max=100,bool $required=false)use($eh){echo '<label class="nf-field">'.$eh($label).'<input type="'.$eh($type).'" name="'.$eh($name).'" value="'.$eh($value).'" maxlength="'.$max.'"'.($required?' required':'').'></label>';};
$receiptFields=function(array $v)use($field,$eh,$user,$mode,$snapshot){
    $selected=(string)($v['counselorName']??($mode==='new'?($user['display_name']??''):''));
    $names=array_values(array_unique(array_merge([$selected],$snapshot['counselorNames']??[])));
    echo '<label class="nf-field">상담원<select name="counselorName" aria-label="상담원 이름">';
    foreach($names as $name)echo '<option value="'.$eh($name).'"'.($name===$selected?' selected':'').'>'.$eh($name===''?'미입력':$name).'</option>';
    echo '</select></label>';echo '<label class="nf-field">성별<select name="gender">';foreach([''=>'미입력','남'=>'남','여'=>'여'] as $value=>$label)echo '<option value="'.$value.'"'.(($v['gender']??'')===$value?' selected':'').'>'.$label.'</option>';echo '</select></label>';$field('callAvailability','통화 가능시간',$v['callAvailability']??'','text',200);$field('visitSchedule','방문 일정·장소',$v['visitSchedule']??'','text',500);};
?>
<?php if(!empty($detailFragment)): if($selected): $r=$selected;require __DIR__.'/partials/intake-detail.php';endif;return;endif ?>
<script src="<?= $eh(asset_url('receipt-form.js')) ?>" defer></script>
<script src="<?= $eh(asset_url('intake-management.js')) ?>" defer></script>
<?php if($error): ?><p class="nf-alert nf-error" role="alert"><?= $eh($error) ?></p><?php endif ?>
<?php if($notice): ?><p class="nf-alert nf-success" role="status"><?= $eh($notice) ?></p><?php endif ?>
<?php if(!$popup): ?><div class="nf-actions"><a class="nf-button" href="<?= $eh(intake_url($filters)) ?>">접수 목록</a><a class="nf-button" href="<?= $eh(intake_url($filters)) ?>#recall-confirmations">정상접수 확인표</a><a class="nf-button primary" href="<?= $eh(intake_url([],['new'=>1])) ?>">접수 등록</a><a href="<?= $eh(intake_url($filters,$selected?['id'=>$selected['id']]:[])) ?>">새로고침</a></div><?php endif ?>
<?php if($mode==='new'): $v=$posted; ?>
<section class="nf-card"><h2>새 접수 등록</h2><p class="nf-muted">담당 직원의 소속 부서로 가접수 상태로 등록합니다. 테스트 직원 계정은 테스트 자료로 구분됩니다.</p>
<form method="post" class="intake-form" data-intake-create action="<?= $eh(intake_url([],['new'=>1])) ?>"><?= native_csrf() ?><input type="hidden" name="action" value="create"><input type="hidden" name="requestKey" value="<?= $eh($requestKey) ?>">
<div class="nf-grid nf-grid-3"><label class="nf-field">담당 직원<select name="employeeId" required><option value="">직원 선택</option><?php foreach($snapshot['staff'] as $staff): ?><option value="<?= (int)$staff['id'] ?>" <?= (string)($v['employeeId']??'')===(string)$staff['id']?'selected':'' ?>><?= $eh($staff['name'].' · '.($teams[$staff['team']]??'')) ?></option><?php endforeach ?></select></label>
<?php $field('date','접수일',$v['date']??hr_today(),'date',10,true);$field('customer','고객명',$v['customer']??'','text',100,true);$field('phone','전화번호',$v['phone']??'','tel',15,true);$field('birthDate','생년월일',$v['birthDate']??'','date',10,true);$field('consultationTime','상담 시간',$v['consultationTime']??(new DateTimeImmutable('now',new DateTimeZone('Asia/Seoul')))->format('H:i'),'time',5);$field('carrier','접수 코드 · 거래처',$v['carrier']??'','text',100); ?>
<label class="nf-field">현재 납부 보험료<select name="premiumBand"><?php foreach($premium as $key=>$label): ?><option value="<?= $key ?>" <?= (string)($v['premiumBand']??'')===(string)$key?'selected':'' ?>><?= $label ?></option><?php endforeach ?></select></label>
<?php $field('consultationPlace','지역(동)',$v['consultationPlace']??'','text',500);$receiptFields($v); ?>
<label class="nf-field nf-full">접수 메모<textarea name="note" maxlength="1000" rows="2"><?= $eh($v['note']??'') ?></textarea></label></div><p class="nf-muted">보험 일반·실버 구분은 접수일 기준 세는나이로 자동 계산합니다.</p><div class="nf-actions"><button class="primary" type="submit" data-receipt-pointer-save>가접수 등록</button></div></form></section>
<?php if(!empty($duplicateCount)): ?><dialog data-native-duplicate class="cnc-admin-save-confirm" aria-label="중복 접수 확인"><h2>중복 접수 확인</h2><p>같은 이름과 전화번호의 기존 접수가 <?= (int)$duplicateCount ?>건 있습니다. 저장하면 고객명 뒤에 (중복)을 붙입니다.</p><div class="cnc-admin-save-confirm-actions"><button type="button" class="secondary" data-native-duplicate-cancel autofocus>취소</button><button type="button" class="primary" data-native-duplicate-save>저장</button></div></dialog><?php endif ?>
<?php else: ?>
<?php if(!$popup): ?><section class="nf-card"><form method="get" class="intake-toolbar"><input type="hidden" name="role" value="admin">
<?php $field('month','조회 월',$filters['month'],'month',7,true);$field('from','시작일',$filters['from'],'date',10);$field('to','종료일',$filters['to'],'date',10); ?>
<label class="nf-field">부서<select name="team"><?php foreach($teams as $key=>$label): ?><option value="<?= $key ?>" <?= $filters['team']===$key?'selected':'' ?>><?= $label ?></option><?php endforeach ?></select></label>
<label class="nf-field">담당 직원<select name="employee"><option value="">전체 직원</option><?php foreach($snapshot['staff'] as $staff): ?><option value="<?= (int)$staff['id'] ?>" <?= $filters['employee']===(string)$staff['id']?'selected':'' ?>><?= $eh($staff['name']) ?></option><?php endforeach ?></select></label>
<label class="nf-field">승인 상태<select name="status"><?php foreach($statuses as $key=>$label): ?><option value="<?= $key ?>" <?= $filters['status']===$key?'selected':'' ?>><?= $label ?></option><?php endforeach ?></select></label>
<label class="nf-field">자료 구분<select name="scope"><?php foreach(['real'=>'운영 자료','test'=>'테스트 자료','all'=>'전체 (테스트 포함)'] as $key=>$label): ?><option value="<?= $key ?>" <?= $filters['scope']===$key?'selected':'' ?>><?= $label ?></option><?php endforeach ?></select></label>
<label class="nf-field intake-search">이름 또는 전화번호<input name="q" value="<?= $eh($filters['q']) ?>" maxlength="80" placeholder="고객 이름 또는 전화번호 입력"></label><button type="submit">조회</button><a href="<?= $eh(intake_url()) ?>">초기화</a></form></section>
<div class="intake-summary"><a href="<?= $eh(intake_url($filters,['status'=>'','p'=>1])) ?>">전체 상태<strong><?= number_format(array_sum($counts)) ?>건</strong></a><?php foreach($counts as $status=>$count): ?><a href="<?= $eh(intake_url($filters,['status'=>$status,'p'=>1])) ?>"><?= intake_status($status) ?><strong><?= number_format($count) ?>건</strong></a><?php endforeach ?></div>
<?php if($filters['scope']!=='real'): ?><p class="nf-alert">테스트 자료<?= $filters['scope']==='all'?'가 포함된 조회':' 조회' ?>입니다. 실제 실적과 구분해 확인해 주세요.</p><?php elseif($testCount): ?><p class="nf-muted">별도로 저장된 테스트 자료 <?= number_format($testCount) ?>건 · <a href="<?= $eh(intake_url($filters,['scope'=>'test','p'=>1])) ?>">테스트 자료 보기</a></p><?php endif ?>
<?php endif ?>
<?php if($selected&&($popup||!in_array($selected['id'],array_column($list,'id'),true))): if(!$popup): ?><p class="nf-muted">선택한 접수는 현재 조회 조건에 포함되지 않아 별도로 표시합니다.</p><?php endif;$r=$selected;require __DIR__.'/partials/intake-detail.php';endif ?>
<?php if(!$popup): ?><section class="nf-card"><div class="nf-actions"><h2>접수 목록 · <?= number_format($total) ?>건</h2><a class="nf-button" href="<?= $eh(intake_url($filters,['export'=>'csv'])) ?>">조회 내역 CSV 내려받기</a></div><?php if($filters['q']!==''): ?><p class="nf-muted intake-search-result">“<?= $eh($filters['q']) ?>” 검색 결과 <?= number_format($total) ?>건 · 같은 이름이나 전화번호의 접수도 모두 표시합니다.</p><?php endif ?><p class="nf-muted">행을 누르면 아래에 접수 내용이 펼쳐집니다. 상담원과 승인 상태를 변경한 뒤 저장해 주세요.</p><div class="nf-table-wrap"><table class="nf-table intake-list"><thead><tr><th>접수일</th><th>담당자·부서</th><th>상담원</th><th>고객명</th><th>전화번호</th><th>접수 코드</th><th>상담 시간·장소</th><th>승인 상태</th><th>상세</th></tr></thead><tbody>
<?php foreach($list as $r): $detailId='intake-detail-'.preg_replace('/[^A-Za-z0-9_-]/','-',$r['id']);$expanded=$selected&&$selected['id']===$r['id'];$detailUrl=intake_url($filters,['id'=>$r['id'],'detail'=>1]); ?>
<tr data-intake-row data-intake-id="<?= $eh($r['id']) ?>" data-intake-url="<?= $eh($detailUrl) ?>" class="<?= $expanded?'is-expanded':'' ?>"><td><?= $eh($r['date']) ?></td><td><?= $eh($r['employee']) ?><br><small><?= $eh($teams[$r['team']]??$r['team']) ?></small></td><td><?= $eh(($r['counselorName']??'')?:'—') ?></td><td><?= $eh($r['customer']) ?><?= $r['isTest']?'<span class="intake-test">테스트</span>':'' ?></td><td><?= $eh($r['phone']??'—') ?></td><td><?= $eh($r['carrier']??'—') ?></td><td><?= $eh(($r['consultationTime']??'').' '.mb_strimwidth($r['consultationPlace']??'',0,44,'…')) ?></td><td><span class="intake-status <?= $eh($r['status']) ?>"><?= intake_status($r['status']) ?></span></td><td><a data-intake-toggle aria-expanded="<?= $expanded?'true':'false' ?>" aria-controls="<?= $eh($detailId) ?>" href="<?= $eh(intake_url($filters,['id'=>$r['id']])) ?>"><?= $expanded?'접기':'보기·수정' ?></a></td></tr>
<tr id="<?= $eh($detailId) ?>" data-intake-detail<?= $expanded?' data-intake-loaded="true"':' hidden' ?>><td colspan="9"><div data-intake-content><?php if($expanded): require __DIR__.'/partials/intake-detail.php';endif ?></div></td></tr>
<?php endforeach ?>
<?php if(!$list): ?><tr><td colspan="9">조회 조건에 맞는 접수가 없습니다.</td></tr><?php endif ?></tbody></table></div><div class="intake-pagination"><?php if($filters['p']>1): ?><a href="<?= $eh(intake_url($filters,['p'=>$filters['p']-1])) ?>">이전</a><?php endif ?><span><?= $filters['p'] ?> / <?= $pages ?> 페이지</span><?php if($filters['p']<$pages): ?><a href="<?= $eh(intake_url($filters,['p'=>$filters['p']+1])) ?>">다음</a><?php endif ?></div></section>
<details class="nf-card intake-recall-card" id="recall-confirmations"><summary>정상접수 확인표 <span class="intake-recall-count"><?= number_format(count($recallQueue)) ?>건</span></summary><p class="nf-muted">직원이 재콜 수정을 요청한 가접수입니다. 전체 월에서 자료 구분·부서·담당 직원·검색어를 적용하고, 오래된 접수부터 표시합니다.</p>
<div class="nf-table-wrap"><table class="nf-table intake-recall-table"><thead><tr><th>최초 접수일</th><th>재콜 요청일시</th><th>담당자·고객</th><th>연락처·상담 장소</th><th>요청 접수 코드</th><th>재콜 메모</th><th>확인·처리</th></tr></thead><tbody>
<?php foreach($recallQueue as $r): $request=$r['recall'];$queueTarget=intake_url(array_replace($filters,['month'=>substr($r['date'],0,7),'from'=>'','to'=>'']),['id'=>$r['id']]); ?>
<tr><td><?= $eh($r['date']) ?><?= $r['isTest']?'<span class="intake-test">테스트</span>':'' ?></td><td><?= $eh(substr(intake_time($request['created_at']),0,16)) ?></td><td><strong><?= $eh($r['customer']) ?></strong><br><small><?= $eh($r['employee'].' · '.($teams[$r['team']]??$r['team'])) ?></small></td><td><?= $eh($r['phone']?:'미입력') ?><br><small><?= $eh($r['consultationPlace']?:'장소 미입력') ?></small></td><td><?= $eh($request['carrier']?:$r['carrier']) ?></td><td class="intake-recall-memo"><?= nl2br($eh($request['reason'])) ?><br><a href="<?= $eh($queueTarget) ?>">상세·기존 메모 보기</a></td><td><details class="intake-recall-process"><summary>확인·처리</summary>
<form method="post" action="<?= $eh($queueTarget) ?>" class="intake-recall-actions"><?= native_csrf() ?><input type="hidden" name="action" value="status"><input type="hidden" name="status" value="normal"><input type="hidden" name="id" value="<?= $eh($r['id']) ?>"><input type="hidden" name="revision" value="<?= (int)$r['revision'] ?>"><input type="hidden" name="recallEventId" value="<?= (int)$request['id'] ?>"><label class="nf-field">확인 메모 (선택)<input name="reason" maxlength="500" placeholder="확인 내용 입력"></label><button class="primary" type="submit">정상접수 확인</button></form>
<form method="post" action="<?= $eh($queueTarget) ?>" class="intake-recall-actions"><?= native_csrf() ?><input type="hidden" name="action" value="hold"><input type="hidden" name="status" value="pending"><input type="hidden" name="id" value="<?= $eh($r['id']) ?>"><input type="hidden" name="revision" value="<?= (int)$r['revision'] ?>"><input type="hidden" name="recallEventId" value="<?= (int)$request['id'] ?>"><label class="nf-field">가접수 유지 사유<input name="reason" maxlength="500" placeholder="추가 상담·확인 필요 사항"></label><button type="submit">가접수 유지</button></form></details></td></tr>
<?php endforeach ?>
<?php if(!$recallQueue): ?><tr><td colspan="7" class="intake-empty">확인을 기다리는 재콜 요청이 없습니다.</td></tr><?php endif ?></tbody></table></div></details>
<?php endif ?>
<?php endif ?>
