<?php
$teams=[''=>'전체 부서','insurance'=>'보험팀','cosmetics'=>'화장품팀','health'=>'건강보조식품팀'];$statuses=[''=>'전체 상태','pending'=>'가접수','normal'=>'정상접수','as'=>'A/S'];$premium=[''=>'미입력','100000'=>'10만 원 이상','200000'=>'20만 원 이상','300000'=>'30만 원 이상'];
$eh=fn(mixed $v):string=>view_h((string)$v);
$field=function(string $name,string $label,mixed $value='',string $type='text',int $max=100,bool $required=false)use($eh){echo '<label class="nf-field">'.$eh($label).'<input type="'.$eh($type).'" name="'.$eh($name).'" value="'.$eh($value).'" maxlength="'.$max.'"'.($required?' required':'').'></label>';};
?>
<?php if($error): ?><p class="nf-alert nf-error" role="alert"><?= $eh($error) ?></p><?php endif ?>
<?php if($notice): ?><p class="nf-alert nf-success" role="status"><?= $eh($notice) ?></p><?php endif ?>
<div class="nf-actions"><a class="nf-button" href="<?= $eh(intake_url($filters)) ?>">접수 목록</a><a class="nf-button primary" href="<?= $eh(intake_url([],['new'=>1])) ?>">접수 등록</a><a href="<?= $eh(intake_url($filters,$selected?['id'=>$selected['id']]:[])) ?>">새로고침</a></div>
<?php if($mode==='new'): $v=$posted; ?>
<section class="nf-card"><h2>새 접수 등록</h2><p class="nf-muted">담당 직원의 소속 부서로 가접수 상태로 등록합니다. 테스트 직원 계정은 테스트 자료로 구분됩니다.</p>
<form method="post" class="intake-form" action="<?= $eh(intake_url([],['new'=>1])) ?>"><?= native_csrf() ?><input type="hidden" name="action" value="create"><input type="hidden" name="requestKey" value="<?= $eh($requestKey) ?>">
<div class="nf-grid nf-grid-3"><label class="nf-field">담당 직원<select name="employeeId" required><option value="">직원 선택</option><?php foreach($snapshot['staff'] as $staff): ?><option value="<?= (int)$staff['id'] ?>" <?= (string)($v['employeeId']??'')===(string)$staff['id']?'selected':'' ?>><?= $eh($staff['name'].' · '.($teams[$staff['team']]??'')) ?></option><?php endforeach ?></select></label>
<?php $field('date','접수일',$v['date']??hr_today(),'date',10,true);$field('customer','고객명',$v['customer']??'','text',100,true);$field('phone','전화번호',$v['phone']??'','tel',15,true);$field('birthDate','생년월일',$v['birthDate']??'','date',10,true);$field('consultationTime','상담 시간',$v['consultationTime']??(new DateTimeImmutable('now',new DateTimeZone('Asia/Seoul')))->format('H:i'),'time',5);$field('carrier','접수 코드 · 거래처',$v['carrier']??'','text',100); ?>
<label class="nf-field">현재 납부 보험료<select name="premiumBand"><?php foreach($premium as $key=>$label): ?><option value="<?= $key ?>" <?= (string)($v['premiumBand']??'')===(string)$key?'selected':'' ?>><?= $label ?></option><?php endforeach ?></select></label>
<?php $field('consultationPlace','상담 장소',$v['consultationPlace']??'','text',500); ?>
<label class="nf-field nf-full">접수 메모<textarea name="note" maxlength="1000" rows="2"><?= $eh($v['note']??'') ?></textarea></label></div><p class="nf-muted">보험 일반·실버 구분은 접수일 기준 세는나이로 자동 계산합니다.</p><div class="nf-actions"><button class="primary" type="submit">가접수 등록</button></div></form></section>
<?php else: ?>
<section class="nf-card"><form method="get" class="intake-toolbar"><input type="hidden" name="role" value="admin">
<?php $field('month','조회 월',$filters['month'],'month',7,true);$field('from','시작일',$filters['from'],'date',10);$field('to','종료일',$filters['to'],'date',10); ?>
<label class="nf-field">부서<select name="team"><?php foreach($teams as $key=>$label): ?><option value="<?= $key ?>" <?= $filters['team']===$key?'selected':'' ?>><?= $label ?></option><?php endforeach ?></select></label>
<label class="nf-field">담당 직원<select name="employee"><option value="">전체 직원</option><?php foreach($snapshot['staff'] as $staff): ?><option value="<?= (int)$staff['id'] ?>" <?= $filters['employee']===(string)$staff['id']?'selected':'' ?>><?= $eh($staff['name']) ?></option><?php endforeach ?></select></label>
<label class="nf-field">처리 상태<select name="status"><?php foreach($statuses as $key=>$label): ?><option value="<?= $key ?>" <?= $filters['status']===$key?'selected':'' ?>><?= $label ?></option><?php endforeach ?></select></label>
<label class="nf-field">자료 구분<select name="scope"><?php foreach(['real'=>'운영 자료','test'=>'테스트 자료','all'=>'전체 (테스트 포함)'] as $key=>$label): ?><option value="<?= $key ?>" <?= $filters['scope']===$key?'selected':'' ?>><?= $label ?></option><?php endforeach ?></select></label>
<label class="nf-field intake-search">고객·전화번호·담당자·접수 코드·장소<input name="q" value="<?= $eh($filters['q']) ?>" maxlength="80" placeholder="검색어 입력"></label><button type="submit">조회</button><a href="<?= $eh(intake_url()) ?>">초기화</a></form></section>
<div class="intake-summary"><a href="<?= $eh(intake_url($filters,['status'=>'','p'=>1])) ?>">전체 상태<strong><?= number_format(array_sum($counts)) ?>건</strong></a><?php foreach($counts as $status=>$count): ?><a href="<?= $eh(intake_url($filters,['status'=>$status,'p'=>1])) ?>"><?= intake_status($status) ?><strong><?= number_format($count) ?>건</strong></a><?php endforeach ?></div>
<?php if($filters['scope']!=='real'): ?><p class="nf-alert">테스트 자료<?= $filters['scope']==='all'?'가 포함된 조회':' 조회' ?>입니다. 실제 실적과 구분해 확인해 주세요.</p><?php elseif($testCount): ?><p class="nf-muted">별도로 저장된 테스트 자료 <?= number_format($testCount) ?>건 · <a href="<?= $eh(intake_url($filters,['scope'=>'test','p'=>1])) ?>">테스트 자료 보기</a></p><?php endif ?>
<?php if($selected): $r=$selected;$legacy=str_starts_with($r['id'],'test:');$v=$posted&&($posted['action']??'')==='edit'?$posted:$r; ?>
<section class="nf-card"><h2>접수 상세 · <?= $eh($r['customer']) ?> <?= $r['isTest']?'<span class="intake-test">테스트</span>':'' ?></h2><dl class="intake-detail-grid">
<?php foreach(['접수번호'=>$r['id'],'접수일'=>$r['date'],'담당자'=>$r['employee'],'부서'=>$teams[$r['team']],'상태'=>intake_status($r['status']),'생년월일'=>($r['birthDate']??'')?:($r['birthYear']??'미입력'),'고객명'=>$r['customer'],'전화번호'=>$r['phone']??'미입력','상품 구분'=>$r['kind']==='silver'?'실버':($r['kind']==='general'?'일반':'—'),'접수 코드'=>$r['carrier']??'','상담 시간'=>$r['consultationTime']??'','상담 장소'=>$r['consultationPlace']??''] as $label=>$value): ?><div><dt><?= $eh($label) ?></dt><dd><?= $eh($value?:'—') ?></dd></div><?php endforeach ?></dl>
<?php if(!$legacy&&!empty($r['phone'])): $phone=preg_replace('/\D/','',$r['phone']);$duplicates=count(array_filter($snapshot['records'],fn($row)=>$row['id']!==$r['id']&&$row['isTest']===$r['isTest']&&str_starts_with($row['date'],$filters['month'])&&preg_replace('/\D/','',$row['phone']??'')===$phone));if($duplicates): ?><p class="nf-alert">같은 전화번호의 다른 접수가 이달 <?= $duplicates ?>건 있습니다. 중복 여부를 확인하세요.</p><?php endif;endif ?>
<form method="post" action="<?= $eh(intake_url($filters,['id'=>$r['id']])) ?>" class="nf-actions"><?= native_csrf() ?><input type="hidden" name="action" value="status"><input type="hidden" name="id" value="<?= $eh($r['id']) ?>"><input type="hidden" name="revision" value="<?= $eh($posted['revision']??$r['revision']) ?>"><label class="nf-field">처리 상태<select name="status"><?php foreach(array_slice($statuses,1) as $key=>$label): ?><option value="<?= $key ?>" <?= ($posted['status']??$r['status'])===$key?'selected':'' ?>><?= $label ?></option><?php endforeach ?></select></label><label class="nf-field">처리 메모 (선택)<input name="reason" maxlength="500" value="<?= $eh(($posted['action']??'')==='status'?($posted['reason']??''):'') ?>" placeholder="상태 변경 사유"></label><button type="submit">상태 저장</button></form>
<?php if(!$legacy): ?><details <?= ($posted['action']??'')==='edit'?'open':'' ?>><summary>고객·상담 정보 수정</summary><form method="post" class="intake-form" action="<?= $eh(intake_url($filters,['id'=>$r['id']])) ?>"><?= native_csrf() ?><input type="hidden" name="action" value="edit"><input type="hidden" name="id" value="<?= $eh($r['id']) ?>"><input type="hidden" name="revision" value="<?= $eh($posted['revision']??$r['revision']) ?>"><input type="hidden" name="status" value="<?= $eh($r['status']) ?>"><div class="nf-grid nf-grid-3">
<?php $field('customer','고객명',$v['customer']??'','text',100,true);$field('phone','전화번호',$v['phone']??'','tel',15,true);$field('carrier','접수 코드 · 거래처',$v['carrier']??'','text',100);$field('consultationTime','상담 시간',$v['consultationTime']??'','time',5);$field('consultationPlace','상담 장소',$v['consultationPlace']??'','text',500); ?>
<label class="nf-field">현재 납부 보험료<select name="premiumBand"><?php foreach($premium as $key=>$label): ?><option value="<?= $key ?>" <?= (string)($v['premiumBand']??'')===(string)$key?'selected':'' ?>><?= $label ?></option><?php endforeach ?></select></label><label class="nf-field nf-full">접수 메모<textarea name="note" maxlength="1000" rows="2"><?= $eh($v['note']??'') ?></textarea></label><label class="nf-field nf-full">수정 사유 (선택)<input name="reason" maxlength="500" value="<?= $eh(($posted['action']??'')==='edit'?($posted['reason']??''):'') ?>"></label></div><div class="nf-actions"><button type="submit">수정 저장</button></div></form></details><?php else: ?><p class="nf-muted">이전 형식의 테스트 자료는 상태만 변경할 수 있습니다.</p><?php endif ?>
<details class="intake-history"><summary>등록·변경 이력 (최근 <?= count($history) ?>건)</summary><?php if(!$history): ?><p class="nf-muted">아직 기록된 변경 이력이 없습니다.</p><?php endif ?>
<?php $names=['customer_name'=>'고객명','phone'=>'전화번호','carrier'=>'접수 코드','note'=>'접수 메모','consultation_time'=>'상담 시간','consultation_place'=>'상담 장소','premium_band'=>'납부 보험료','status'=>'상태'];foreach($history as $event): ?><section><p><strong><?= $eh(intake_time($event['created_at'])) ?> · <?= $eh($event['actor']) ?></strong> · <?= ['create'=>'접수 등록','status'=>'상태 변경','edit'=>'정보 수정'][$event['action']]??'처리' ?></p><dl><?php foreach($event['after'] as $key=>$value): $before=$event['before'][$key]??'';if($before===$value)continue; ?><dt><?= $eh($names[$key]??$key) ?></dt><dd><?= $eh($key==='status'?intake_status($before):$before) ?> → <?= $eh($key==='status'?intake_status($value):$value) ?></dd><?php endforeach ?></dl><?php if($event['reason']): ?><p>메모: <?= $eh($event['reason']) ?></p><?php endif ?></section><?php endforeach ?></details></section>
<?php endif ?>
<section class="nf-card"><div class="nf-actions"><h2>접수 목록 · <?= number_format($total) ?>건</h2><a class="nf-button" href="<?= $eh(intake_url($filters,['export'=>'csv'])) ?>">조회 내역 CSV 내려받기</a></div><div class="nf-table-wrap"><table class="nf-table intake-list"><thead><tr><th>접수일</th><th>담당자·부서</th><th>고객명</th><th>전화번호</th><th>접수 코드</th><th>상담 시간·장소</th><th>상태</th><th>상세</th></tr></thead><tbody>
<?php foreach($list as $r): ?><tr><td><?= $eh($r['date']) ?></td><td><?= $eh($r['employee']) ?><br><small><?= $eh($teams[$r['team']]) ?></small></td><td><?= $eh($r['customer']) ?><?= $r['isTest']?'<span class="intake-test">테스트</span>':'' ?></td><td><?= $eh($r['phone']??'—') ?></td><td><?= $eh($r['carrier']??'—') ?></td><td><?= $eh(($r['consultationTime']??'').' '.mb_strimwidth($r['consultationPlace']??'',0,44,'…')) ?></td><td><span class="intake-status <?= $eh($r['status']) ?>"><?= intake_status($r['status']) ?></span></td><td><a href="<?= $eh(intake_url($filters,['id'=>$r['id']])) ?>">열기</a></td></tr><?php endforeach ?>
<?php if(!$list): ?><tr><td colspan="8">조회 조건에 맞는 접수가 없습니다.</td></tr><?php endif ?></tbody></table></div><div class="intake-pagination"><?php if($filters['p']>1): ?><a href="<?= $eh(intake_url($filters,['p'=>$filters['p']-1])) ?>">이전</a><?php endif ?><span><?= $filters['p'] ?> / <?= $pages ?> 페이지</span><?php if($filters['p']<$pages): ?><a href="<?= $eh(intake_url($filters,['p'=>$filters['p']+1])) ?>">다음</a><?php endif ?></div></section>
<?php endif ?>
